name: CI Pipeline  # Tên workflow

on:
  push:
    branches: [ main, develop ]  # Trigger khi push vào main hoặc develop
  pull_request:
    branches: [ main, develop ]  # Trigger khi tạo PR vào main hoặc develop

jobs:
  build-and-test:
    runs-on: ubuntu-latest  # Hệ điều hành chạy job

    steps:
      # 1. Checkout code
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Cài Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      # 3. Cài dependencies
      - name: Install dependencies
        run: npm install

      # 4. Chạy test
      - name: Run tests
        run: npm test

      # 5. Build project (nếu có)
      - name: Build project
        run: npm run build
