name: React CI Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout code
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      # 3. Cache node_modules để tăng tốc
      - name: Cache Node modules
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}

      # 4. Cài dependencies
      - name: Install dependencies
        run: npm ci

      # 5. Chạy test
      - name: Run tests
        run: npm test

      # 6. Build project
      - name: Build React app
        run: npm run build

      # 7. Lưu artifact (tùy chọn - để dùng cho deploy)
      - name: Upload production-ready build files
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: build
